---
name: Packer GitHub Actions
author: Matt James
description: Run Packer commands

inputs:
  command:
    description: command to execute
    required: true
  arguments:
    description: arguments for command
    required: false
  working_directory:
    description: working directory for command (defaults to root)
    required: false
  ansible_version:
    description: ansible version
    required: false
    default: 3.2.0
  target:
    description: file(s) or directory to target
    required: false
    default: .

outputs:
  command:
    description: interpolated command (incl. arguments) that will be executed

runs:
  using: "docker"
  image: "docker://ghcr.io/patrontech/packer-ansible-github-actions-container:3.2.0"

branding:
  color: blue
  icon: package
